name: Deploy HTML to GitHub Pages

on:
  push:
    branches: [ main ]  # Déclenche le workflow à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3

        with:
           github_token: ${{ secrets.GH_TOKEN }}   # utiliser le PAT
           publish_dir: ./                          # dossier contenant index.html
           publish_branch: gh-pages
           force_orphan: true        
